### ISSUE TITLE
Row Count

### ISSUE THREAD

**Issue by HaneetGH** [okhanokbay/ExpyTableView#19] opened 2018-01-05 06:16 UTC
Hi,
Section is using array's element of 0th index as a result number of rows count has decreased by 1...its starting from element from element of index 1.

Kindly resolve this or share a solution.
Thanks.

**Comment by okhanokbay** [comment] 2018-02-06 17:36
Duplicate of #12

**Closed as completed by okhanokbay** 2018-02-06 17:36 UTC
