### ISSUE TITLE
Spaces in between section headers

### ISSUE THREAD

**Issue by marknf94** [okhanokbay/ExpyTableView#17] opened 2017-11-16 00:19 UTC
Currently getting space between the section headers when the rows are closed. No spaces appear between the rows under the section. But can't seem to get rid of the spaces between the section headers.

**Comment by okhanokbay** [comment] 2017-11-16 21:32
@marknf94 how to reproduce this please? any sample project or code?

**Comment by okhanokbay** [comment] 2018-02-06 17:31
Closing this since no answer from @marknf94

**Closed as completed by okhanokbay** 2018-02-06 17:31 UTC
